-- migrate:up
ALTER TABLE workflow_runs
  ADD COLUMN IF NOT EXISTS branched_from_attempt_run_id UUID;

UPDATE workflow_runs
SET branched_from_attempt_run_id = branched_from_run_id
WHERE branched_from_attempt_id IS NOT NULL
  AND branched_from_attempt_run_id IS NULL;

ALTER TABLE workflow_runs
  DROP CONSTRAINT IF EXISTS workflow_runs_branched_from_attempt_fkey;

DROP INDEX IF EXISTS workflow_runs_branched_from_attempt_id_idx;

CREATE INDEX IF NOT EXISTS workflow_runs_branched_from_attempt_idx
  ON workflow_runs (branched_from_attempt_run_id, branched_from_attempt_id);

DO $$
DECLARE
  partition_index integer;
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE oid = 'workflow_step_attempts'::regclass
      AND relkind <> 'p'
  ) THEN
    ALTER TABLE workflow_step_attempts RENAME TO workflow_step_attempts_legacy;
    DROP INDEX IF EXISTS workflow_step_attempts_run_id_idx;
    DROP INDEX IF EXISTS workflow_step_attempts_run_id_step_seq_idx;

    CREATE TABLE workflow_step_attempts (
      id UUID NOT NULL DEFAULT gen_random_uuid(),
      run_id UUID NOT NULL REFERENCES workflow_runs (id) ON DELETE CASCADE,
      step_key TEXT NOT NULL,
      kind step_attempt_kind NOT NULL DEFAULT 'forward',
      step_seq INTEGER NOT NULL,
      attempt INTEGER NOT NULL,
      status step_attempt_status NOT NULL,
      context_before JSONB NOT NULL DEFAULT '{}'::jsonb,
      input JSONB NOT NULL DEFAULT '{}'::jsonb,
      output JSONB,
      error JSONB,
      started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_heartbeat_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT workflow_step_attempts_partitioned_pkey PRIMARY KEY (run_id, id),
      CONSTRAINT workflow_step_attempts_partitioned_run_step_key_kind_attempt_key
        UNIQUE (run_id, step_key, kind, attempt)
    ) PARTITION BY HASH (run_id);

    CREATE INDEX workflow_step_attempts_run_id_idx
      ON workflow_step_attempts (run_id, step_key, kind, attempt DESC);

    CREATE UNIQUE INDEX workflow_step_attempts_run_id_step_seq_idx
      ON workflow_step_attempts (run_id, step_seq);

    FOR partition_index IN 0..15 LOOP
      EXECUTE format(
        'CREATE TABLE workflow_step_attempts_p%s PARTITION OF workflow_step_attempts FOR VALUES WITH (modulus 16, remainder %s)',
        lpad(partition_index::text, 2, '0'),
        partition_index
      );
    END LOOP;

    INSERT INTO workflow_step_attempts (
      id,
      run_id,
      step_key,
      kind,
      step_seq,
      attempt,
      status,
      context_before,
      input,
      output,
      error,
      started_at,
      last_heartbeat_at,
      completed_at,
      created_at,
      updated_at
    )
    SELECT
      id,
      run_id,
      step_key,
      kind,
      step_seq,
      attempt,
      status,
      context_before,
      input,
      output,
      error,
      started_at,
      last_heartbeat_at,
      completed_at,
      created_at,
      updated_at
    FROM workflow_step_attempts_legacy
    ORDER BY created_at ASC, id ASC;

    DROP TABLE workflow_step_attempts_legacy;
  END IF;
END
$$;

ALTER TABLE workflow_runs
  DROP CONSTRAINT IF EXISTS workflow_runs_branched_from_attempt_fkey;

ALTER TABLE workflow_runs
  ADD CONSTRAINT workflow_runs_branched_from_attempt_fkey
  FOREIGN KEY (branched_from_attempt_run_id, branched_from_attempt_id)
  REFERENCES workflow_step_attempts (run_id, id)
  ON DELETE SET NULL;

DO $$
DECLARE
  partition_index integer;
  event_sequence_name text;
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE oid = 'workflow_events'::regclass
      AND relkind <> 'p'
  ) THEN
    ALTER TABLE workflow_events RENAME TO workflow_events_legacy;
    DROP INDEX IF EXISTS workflow_events_run_id_idx;

    CREATE TABLE workflow_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      run_id UUID NOT NULL REFERENCES workflow_runs (id) ON DELETE CASCADE,
      step_key TEXT,
      event_type TEXT NOT NULL,
      payload JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT workflow_events_partitioned_pkey PRIMARY KEY (run_id, id)
    ) PARTITION BY HASH (run_id);

    CREATE INDEX workflow_events_run_id_idx
      ON workflow_events (run_id, created_at, id);

    FOR partition_index IN 0..15 LOOP
      EXECUTE format(
        'CREATE TABLE workflow_events_p%s PARTITION OF workflow_events FOR VALUES WITH (modulus 16, remainder %s)',
        lpad(partition_index::text, 2, '0'),
        partition_index
      );
    END LOOP;

    INSERT INTO workflow_events (
      id,
      run_id,
      step_key,
      event_type,
      payload,
      created_at
    )
    SELECT
      id,
      run_id,
      step_key,
      event_type,
      payload,
      created_at
    FROM workflow_events_legacy
    ORDER BY created_at ASC, id ASC;

    event_sequence_name := pg_get_serial_sequence('workflow_events', 'id');

    IF event_sequence_name IS NOT NULL THEN
      EXECUTE format(
        'SELECT setval(%L, COALESCE((SELECT MAX(id) FROM workflow_events), 1), true)',
        event_sequence_name
      );
    END IF;

    DROP TABLE workflow_events_legacy;
  END IF;
END
$$;

COMMENT ON TABLE workflow_step_attempts IS 'Per-step execution attempts for audit and recovery';
COMMENT ON TABLE workflow_events IS 'Append-only workflow event stream';

-- migrate:down
ALTER TABLE workflow_runs
  DROP CONSTRAINT IF EXISTS workflow_runs_branched_from_attempt_fkey;

DROP INDEX IF EXISTS workflow_runs_branched_from_attempt_idx;

DO $$
DECLARE
  event_sequence_name text;
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE oid = 'workflow_events'::regclass
      AND relkind = 'p'
  ) THEN
    ALTER TABLE workflow_events RENAME TO workflow_events_partitioned_legacy;
    DROP INDEX IF EXISTS workflow_events_run_id_idx;

    CREATE TABLE workflow_events (
      id BIGSERIAL PRIMARY KEY,
      run_id UUID NOT NULL REFERENCES workflow_runs (id) ON DELETE CASCADE,
      step_key TEXT,
      event_type TEXT NOT NULL,
      payload JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE INDEX workflow_events_run_id_idx
      ON workflow_events (run_id, created_at);

    INSERT INTO workflow_events (
      id,
      run_id,
      step_key,
      event_type,
      payload,
      created_at
    )
    SELECT
      id,
      run_id,
      step_key,
      event_type,
      payload,
      created_at
    FROM workflow_events_partitioned_legacy
    ORDER BY created_at ASC, id ASC;

    event_sequence_name := pg_get_serial_sequence('workflow_events', 'id');

    IF event_sequence_name IS NOT NULL THEN
      EXECUTE format(
        'SELECT setval(%L, COALESCE((SELECT MAX(id) FROM workflow_events), 1), true)',
        event_sequence_name
      );
    END IF;

    DROP TABLE workflow_events_partitioned_legacy;
  END IF;
END
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE oid = 'workflow_step_attempts'::regclass
      AND relkind = 'p'
  ) THEN
    ALTER TABLE workflow_step_attempts RENAME TO workflow_step_attempts_partitioned_legacy;
    DROP INDEX IF EXISTS workflow_step_attempts_run_id_idx;
    DROP INDEX IF EXISTS workflow_step_attempts_run_id_step_seq_idx;

    CREATE TABLE workflow_step_attempts (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      run_id UUID NOT NULL REFERENCES workflow_runs (id) ON DELETE CASCADE,
      step_key TEXT NOT NULL,
      kind step_attempt_kind NOT NULL DEFAULT 'forward',
      step_seq INTEGER NOT NULL,
      attempt INTEGER NOT NULL,
      status step_attempt_status NOT NULL,
      context_before JSONB NOT NULL DEFAULT '{}'::jsonb,
      input JSONB NOT NULL DEFAULT '{}'::jsonb,
      output JSONB,
      error JSONB,
      started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_heartbeat_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT workflow_step_attempts_run_id_id_key UNIQUE (run_id, id),
      UNIQUE (run_id, step_key, kind, attempt)
    );

    CREATE INDEX workflow_step_attempts_run_id_idx
      ON workflow_step_attempts (run_id, step_key, kind, attempt DESC);

    CREATE UNIQUE INDEX workflow_step_attempts_run_id_step_seq_idx
      ON workflow_step_attempts (run_id, step_seq);

    INSERT INTO workflow_step_attempts (
      id,
      run_id,
      step_key,
      kind,
      step_seq,
      attempt,
      status,
      context_before,
      input,
      output,
      error,
      started_at,
      last_heartbeat_at,
      completed_at,
      created_at,
      updated_at
    )
    SELECT
      id,
      run_id,
      step_key,
      kind,
      step_seq,
      attempt,
      status,
      context_before,
      input,
      output,
      error,
      started_at,
      last_heartbeat_at,
      completed_at,
      created_at,
      updated_at
    FROM workflow_step_attempts_partitioned_legacy
    ORDER BY created_at ASC, id ASC;

    DROP TABLE workflow_step_attempts_partitioned_legacy;
  END IF;
END
$$;

ALTER TABLE workflow_runs
  ADD CONSTRAINT workflow_runs_branched_from_attempt_fkey
  FOREIGN KEY (branched_from_attempt_run_id, branched_from_attempt_id)
  REFERENCES workflow_step_attempts (run_id, id)
  ON DELETE SET NULL;

CREATE INDEX workflow_runs_branched_from_attempt_idx
  ON workflow_runs (branched_from_attempt_run_id, branched_from_attempt_id);
